iter19 | add doc

diff --git a/.github/workflows/mertricstest.yml b/.github/workflows/mertricstest.yml
--- a/.github/workflows/mertricstest.yml
+++ b/.github/workflows/mertricstest.yml
@@ -436,6 +436,38 @@ jobs:
             goimports -l .
             exit 1
           fi
+      - name: "Code increment #19"
+        if: |
+          github.head_ref == 'iter19'
+        run: |
+          for pkg in internal/storage internal/handlers internal/middleware internal/audit internal/agent internal/server pkg/hash; do
+            if [ -f "$pkg/doc.go" ]; then
+              echo "$pkg/doc.go not found"
+            else
+              echo "$pkg/doc.go not found"
+              exit 1
+            fi
+          done
+
+         
+          go test -v ./internal/handlers/ -run Example
+          go test -v ./internal/storage/ -run Example
+          go test -v ./internal/middleware/ -run Example
+
+          go doc github.com/Eressleep/metrics-tpl/internal/storage
+          go doc github.com/Eressleep/metrics-tpl/internal/handlers
+          go doc github.com/Eressleep/metrics-tpl/internal/middleware
+          go doc github.com/Eressleep/metrics-tpl/internal/audit
+          go doc github.com/Eressleep/metrics-tpl/internal/agent
+          go doc github.com/Eressleep/metrics-tpl/internal/server
+          go doc github.com/Eressleep/metrics-tpl/pkg/hash
+
+        
+          go doc github.com/Eressleep/metrics-tpl/internal/storage.Storage
+          go doc github.com/Eressleep/metrics-tpl/internal/handlers.MetricsHandler
+          go doc github.com/Eressleep/metrics-tpl/internal/audit.Auditor
+          go doc github.com/Eressleep/metrics-tpl/internal/agent.Agent
+          go doc github.com/Eressleep/metrics-tpl/internal/server.Server
 
       - name: "Race detection"
         if: |
@@ -444,7 +476,8 @@ jobs:
           github.head_ref == 'iter15' ||
           github.head_ref == 'iter16' ||
           github.head_ref == 'iter17' ||
-          github.head_ref == 'iter18'
+          github.head_ref == 'iter18' ||
+          github.head_ref == 'iter19'
         run: |
           go test -v -race ./...
 
